### ISSUE TITLE
Consider renaming "SDK" to "Adview"

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-protocol#17]
in adtech, "SDK" is commonly used, but in our case it's merely a component to show an ad for now

**Comment by dmngdsm** [comment]
It took me some time to understand, that by SDK we don't mean Software Development Kit, being not familiar with Ad tech jargon. Probably switching to adview is really better :

"SDKAcronym for “Software Development Kit”; in the classic software development sense, a SDK is a set of software development tools that enable a developer to create applications for a specific platform i.e. Apple’s iOS or Google’s Android platform; in mobile ad tech however, a SDK is simply a piece of code placed in mobile apps that enables communication with the publisher’s application and advertising software platforms. SDKs have a wide range of uses among them analytics and monetization of mobile applications. Whereas an API serves standard and native formats, an SDK serves interstitial and rich media formats."

**Comment by Dylanoshi** [comment]
i would 100% agree

**Comment by Ivshti** [comment]
the way adtech uses the term SDK is not necessarily wrong btw, it's just skewed

but  the consensus seems to be that "adview" is better

There's also this: we shouldn't rename things just because we think we can name them better; but in this case, most people just copy-paste a HTML and don't care what's it named, and developers will find "adview manager" more immediately obvious and understandable
