### ISSUE TITLE
Self-sovreign Identity plugin.

### ISSUE THREAD

**Issue by phoniks** [AdExNetwork/adex-protocol#25]
Hey there!  I'm a fellow in the Decentralized Consensus program at [Insight](insightdatascience.com), and I'm working on coming up with a project to demo to potential employers in a few weeks.  I'm very interested in the concept of advertising in a decentralized paradigm, so I was very excited to come across the AdEx protocol, and discover that it's open source.  The problem that I was hoping to explore, specifically, was the question of what role self-sovereign identity plays in this new ecosystem.  I discovered issue #10 about identity that @Ivshti  was working on, but if I'm reading correctly the concept of identity being discussed there is particular to this project. Nevertheless, it seems like there's the potential to plug in support for SSI - perhaps the user could instantiate the adex identity contract by signing in with a DID (uPort, everynym, hyperledger Indy etc).  I'd be curious to hear thoughts on whether there would be any value to that, and what some of the practical hurdles to implementing such a thing might be.

**Comment by Ivshti** [comment]
the Identity is implemented in https://github.com/adexnetwork/adex-protocol-eth, and currently provides 2 core functionalities
1) using multiple keypairs under one account
2) gas abstractions

I guess the first usecase is where uPort/etc. could be plugged in

depending on the use case, it might be valuable, but we're not that familiar with any of those projects

integrations could be valuable if

1) the project in question has significant adoption
2) the project in question is integrated in a popular web browser
